title: "Kansasaja의 노트북"
description: "수학, 컴퓨팅, 물리, 엔지니어링 등에 대한 생각들"
url: "https://kansasaja.github.io"
baseurl: ""

# Theme
theme: minimal-mistakes-jekyll

# Site Author
author:
  name: "Kansasaja"
  bio: "수학, 컴퓨팅, 물리, 엔지니어링 등에 대한 생각들을 나누는 공간입니다."
  location: "Korea"
  email: "your@email.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kansasaja"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your@email.com"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

# Locale
locale: "ko-KR"

# Minimal Mistakes skin
minimal_mistakes_skin: "default"

# Site Search
search: true
